pipeline {
    agent any

    environment {
        IMAGE_NAME = "ashishmondal420/lab23-jenkins-cicd"
        CONTAINER_NAME = "lab23-jenkins-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:latest .'
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                      docker push $IMAGE_NAME:latest
                    '''
                }
            }
        }

        stage('Deploy (CD)') {
            steps {
                sh '''
                  docker rm -f $CONTAINER_NAME || true
                  docker run -d -p 3000:3000 --name $CONTAINER_NAME $IMAGE_NAME:latest
                '''
            }
        }

        stage('Verify') {
            steps {
                sh 'curl -f http://localhost:3000'
            }
        }
    }
}
