pipeline {
    agent any

    environment {
        IMAGE_NAME = "ashishmondal420/lab23-jenkins-cicd"
        CONTAINER_NAME = "lab23-jenkins-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
            sh '''
          docker build \
            -t $IMAGE_NAME:latest \
            -f lab-23-jenkins-docker-build/Dockerfile \
            lab-23-jenkins-docker-build
        '''
            }
        }

stage('Push Image') {
    steps {
        withCredentials([usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
        )]) {
            sh '''
              docker images | grep lab23-jenkins-cicd
              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
              docker push $IMAGE_NAME:latest
            '''
        }
    }
}

    stage('Deploy (CD)') {
            steps {
               sh '''
          echo "Stopping old container if exists..."
          docker rm -f lab23-jenkins-app || true

          echo "Removing old image (safety)..."
          docker rmi -f ashishmondal420/lab23-jenkins-cicd:latest || true

          echo "Pulling latest image..."
          docker pull ashishmondal420/lab23-jenkins-cicd:latest

          echo "Starting new container..."
          docker run -d -p 3000:3000 --name lab23-jenkins-app ashishmondal420/lab23-jenkins-cicd:latest
        '''
            }
        }

        stage('Verify') {
            steps {
                sh 'curl -f http://localhost:3000'
            }
        }
    }
}
