pipeline {
    agent any

    environment {
        IMAGE_NAME = "ashishmondal420/lab23-jenkins-cicd"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Push Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                      docker build -t $IMAGE_NAME:latest \
                        -f lab-23-jenkins-docker-build/Dockerfile \
                        lab-23-jenkins-docker-build

                      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                      docker push $IMAGE_NAME:latest
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes (Rolling Update)') {
            steps {
                sh '''
                  sudo -u ashish kubectl apply -f lab-25-jenkins-k8s-deploy/k8s/deployment.yaml
                  sudo -u ashish kubectl apply -f lab-25-jenkins-k8s-deploy/k8s/service.yaml
                  sudo -u ashish kubectl rollout status deployment/lab25-jenkins-app
                '''
            }
        }
    }
}
