pipeline {
    agent any

    environment {
        IMAGE = "ashishmondal420/lab29"
        TAG = "v1"
        RELEASE = "lab29"
        CHART = "helm/lab29"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Ashish420-tech/azure-devops-50-realworld-labs.git'
            }
        }

        stage('Build & Push Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'U',
                    passwordVariable: 'P'
                )]) {
                    sh '''
                    docker build -t $IMAGE:$TAG app/
                    echo $P | docker login -u $U --password-stdin
                    docker push $IMAGE:$TAG
                    '''
                }
            }
        }

        stage('Deploy with Helm') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                    sh 'helm upgrade --install $RELEASE $CHART'
                }
            }
        }
    }

    post {
        success { echo "✅ Deployment successful" }
        failure { echo "❌ Deployment failed" }
    }
}
