pipeline {
    agent any

    environment {
        IMAGE   = "ashishmondal420/lab29"
        TAG     = "v1"
        RELEASE = "lab29"
        CHART   = "helm/lab29"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                dir('lab-29-jenkins-kubernetes') {
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh '''
                        docker build -t $IMAGE:$TAG app
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $IMAGE:$TAG
                        '''
                    }
                }
            }
        }

        stage('Deploy with Helm') {
            steps {
                dir('lab-29-jenkins-kubernetes') {
                    withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                        sh '''
                        helm upgrade --install $RELEASE $CHART \
                          --set image.repository=$IMAGE \
                          --set image.tag=$TAG
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo "✅ Lab 29 deployment successful"
        }
        failure {
            echo "❌ Lab 29 deployment failed"
        }
    }
}
